spring:
  application:
    name: medical-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/phr
    username: postgres
    password: password
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

# Move eureka config out of spring
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostname: localhost

server:
  port: 8083